[package]
name = "essentia"
version = "0.1.0"
edition = "2024"

[dependencies]
essentia-core = { path = "../essentia_core" }
thiserror = "1.0"

[build-dependencies]
essentia-codegen = { path = "../essentia_codegen" }
