[package]
name = "essentia"
version = "0.1.0"
edition = "2024"

[dependencies]
cxx = "1.0.160"
essentia-core = { path = "../essentia_core", version = "=0.1.0"}
thiserror = "2.0.12"

[build-dependencies]
essentia-codegen = { path = "../essentia_codegen" }
