name: Rust Build with Essentia

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    container: lagmoellertim/essentia:latest-tensorflow
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true