name: Rust Build with Essentia

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: lagmoellertim/essentia:latest-tensorflow
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install curl and wget
      run: |
        apt-get update
        apt-get install -y curl wget pkg-config build-essential
        
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
    
    - name: Build essentia_core
      run: |
        cargo build