name: Release and Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 0.1.1, 0.2.0)'
        required: true
        type: string
      release_type:
        description: 'Type of release'
        required: true
        default: 'patch'
        type: choice
        options:
        - patch
        - minor
        - major

jobs:
  release:
    runs-on: ubuntu-latest
    container: lagmoellertim/essentia:latest-tensorflow
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
      
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y curl wget pkg-config build-essential git
        
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
        components: rustfmt, clippy

    - name: Install cargo-edit for version bumping
      run: |
        cargo install cargo-edit --locked

    - name: Update versions in all Cargo.toml files
      run: |
        VERSION="${{ github.event.inputs.version }}"
        echo "Updating all crates to version $VERSION"
        
        # Update workspace member versions
        cargo set-version -p essentia-sys $VERSION
        cargo set-version -p essentia-core $VERSION
        cargo set-version -p essentia-codegen $VERSION
        cargo set-version -p essentia $VERSION
        
        # Update internal dependencies to use new versions
        cd essentia_core
        cargo add essentia-sys@$VERSION --path ../essentia_sys
        cd ../essentia_codegen
        cargo add essentia-core@$VERSION --path ../essentia_core
        cd ../essentia
        cargo add essentia-core@$VERSION --path ../essentia_core
        cargo add essentia-codegen@$VERSION --path ../essentia_codegen --build
        cd ..

    - name: Update Cargo.lock
      run: |
        cargo check --all

    - name: Run tests to ensure everything works
      run: |
        cargo test --all --verbose

    - name: Build release version
      run: |
        cargo build --release --all

    - name: Generate documentation
      run: |
        cargo doc --no-deps --all-features --workspace
        
    - name: Create git tag and commit
      run: |
        VERSION="${{ github.event.inputs.version }}"
        git add .
        git commit -m "chore: bump version to $VERSION" || echo "No changes to commit"
        git tag -a "v$VERSION" -m "Release version $VERSION"

    - name: Check if version is already published
      id: check_version
      run: |
        VERSION="${{ github.event.inputs.version }}"
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        
        # Check if this version is already published
        if cargo search essentia --limit 1 | grep -q "essentia = \"$VERSION\""; then
          echo "already_published=true" >> $GITHUB_OUTPUT
          echo "Version $VERSION is already published"
        else
          echo "already_published=false" >> $GITHUB_OUTPUT
          echo "Version $VERSION is not yet published"
        fi

    - name: Dry run publish
      if: steps.check_version.outputs.already_published == 'false'
      run: |
        echo "Running dry-run publish for all packages..."
        cargo publish --dry-run -p essentia-sys
        cargo publish --dry-run -p essentia-core
        cargo publish --dry-run -p essentia-codegen
        cargo publish --dry-run -p essentia

    - name: Publish to crates.io
      if: steps.check_version.outputs.already_published == 'false'
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      run: |
        VERSION="${{ github.event.inputs.version }}"
        echo "Publishing packages to crates.io version $VERSION..."
        
        # Publish in dependency order with proper error handling
        echo "Publishing essentia-sys..."
        cargo publish -p essentia-sys --token $CARGO_REGISTRY_TOKEN
        
        echo "Waiting for essentia-sys to be available..."
        sleep 30
        
        echo "Publishing essentia-core..."
        cargo publish -p essentia-core --token $CARGO_REGISTRY_TOKEN
        
        echo "Waiting for essentia-core to be available..."
        sleep 30
        
        echo "Publishing essentia-codegen..."
        cargo publish -p essentia-codegen --token $CARGO_REGISTRY_TOKEN
        
        echo "Waiting for essentia-codegen to be available..."
        sleep 30
        
        echo "Publishing essentia..."
        cargo publish -p essentia --token $CARGO_REGISTRY_TOKEN

    - name: Push git changes and tags
      if: steps.check_version.outputs.already_published == 'false'
      run: |
        git push origin main
        git push origin --tags

    - name: Create GitHub Release
      if: steps.check_version.outputs.already_published == 'false'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.event.inputs.version }}
        release_name: Release v${{ github.event.inputs.version }}
        body: |
          ## Release v${{ github.event.inputs.version }}
        draft: false
        prerelease: false
